services:
  smart-parking-api:
    image: "smart-parking-api"
    build: .
    container_name: smart-parking-api
    ports:
      - 55555:8080
    volumes:
      - C:\Users\EI CHANUDOM\OneDrive\Pictures\file-server:/file-server/
    networks:
      - smart-parking-net
    depends_on:
      - smart-parking-system-db

  smart-parking-system-db:
    image: postgres:16.4-alpine3.20
    container_name: smart-parking-system-db
    ports:
      - 5555:5432
    environment:
      POSTGRES_USER: udom
      POSTGRES_PASSWORD: Domkh@#12
      POSTGRES_DB: smart-parking-system-db
    volumes:
      - smart-parking-system-db:/var/lib/postgresql/data
    networks:
      - smart-parking-net

volumes:
  smart-parking-system-db:

networks:
  smart-parking-net:
    driver: bridge